---
title: "NOAA Fisheries National PAM Archiving at NCEI"
page-layout: full
---

## Project 1: [National PAM Archiving](https://nmfs-ost.github.io/PAM-NCEI/content/archive.html)

The NCEI Passive Acoustic Data (PAD) Archive team will work collaboratively with each NMFS FMC to develop configurable tools that will facilitate FMCs to prepare numerous datasets in a more automated way for archiving at NCEI. This will allow this collective group to meet the PAM SI goal of archiving 900 TB of data in three years (Objective 3) and make significant progress towards meeting NOAA PARR requirements.

### Goals

Build efficient workflows to archive large volumes of NMFS PAM data and meet the projected data growth needs

### Action Items

-   Archive Breakdown
-   FLAC Check
-   Kourtney's Kode
-   Metadata Madness
-   Bracing for the Data Tsunami
-   Call Me Maybe



## Project 2: [Native to FLAC Conversion](https://nmfs-ost.github.io/PAM-NCEI/content/Flac.html)

Storing and processing audio data as FLAC files, a lossless compression format for audio data, saves substantial storage space and processing time. Fully integrating FLAC files into the PAM processing and storage workflow would require additional investment beyond the current PAM SI funding to develop software to convert from native to FLAC and ensure that common processing softwares accept FLAC formats. The PAM SI team will leverage existing effort to make progress towards this project as possible, but it is currently unfunded.

The goal of this effort will be to eliminate the time-consuming step of converting native audio files into wav and then into FLAC by creating a workflow that directly converts native files into a FLAC format. It will also make progress on ensuring FLAC files will be accepted inputs from some of the most commonly used processing software.

### Goal
A more time-efficient workflow that omits steps in the file conversion process prior to archiving

-   [Convert to FLAC](https://nmfs-ost.github.io/PAM-NCEI/content/convertFlac.html)
-   [Process FLAC](https://nmfs-ost.github.io/PAM-NCEI/content/processFlac.html)
