---
title: PAM Data Archive
---

## Goal

Build efficient workflows to archive large volumes of NMFS PAM data and meet the projected data growth needs

## Summary

The NCEI Passive Acoustic Data (PAD) Archive team will work collaboratively with each NMFS FMC to develop configurable tools that will facilitate FMCs to prepare numerous datasets in a more automated way for archiving at NCEI. This will allow this collective group to meet the PAM SI goal of archiving 900 TB of data in three years (Objective 3) and make significant progress towards meeting NOAA PARR requirements.

## Action items

Archive Breakdown: FMCs are asked to update this spreadsheet with revised information based on the original table of datasets to archive found in PAM SI proposal / slide 12. The request is to provide more details on prioritized datasets, target month(s) for data submission, identify POCs to work with the archive team, and describe how metadata are stored (e.g., spreadsheet, Oracle database).

-   FLAC Check: Confirm FLAC conversion doesn’t alter audio values with Peter Dugan.

-   Kourtney’s Kode: Kourtney will share her Passive Packer process - using semi automated code to convert deployment metadata spreadsheet to Passive Packer ready database.

-   Metadata Madness: Meeting with NCEI PAD team, Kourtney, Jeff Walker, and Genevieve Davis to review metadata fields and ensure alignment between NCEI Passive Packer / Kourtney’s code /PACM.

-   Bracing for the Data Tsunami: NCEI PAD team assesses data prioritization and metadata information provided by the FMCs (Action 1) and outlines a plan for building the necessary capabilities into Passive Packer and the archive pipeline.

-   Call Me Maybe: Establish bimonthly meetings with NCEI PAD team and POCs to ensure regular communication regarding progress of archive development tasks and FMC dataset preparation.
